# Project: Juego_1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"C:/Program Files/WindowsApps/51896DevPackager.DevCPP-CIDE_1.0.0.0_x64__6c850yt9hf1bg/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/lib" -L"C:/Program Files/WindowsApps/51896DevPackager.DevCPP-CIDE_1.0.0.0_x64__6c850yt9hf1bg/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -lwinmm -g3
INCS     = -I"C:/Program Files/WindowsApps/51896DevPackager.DevCPP-CIDE_1.0.0.0_x64__6c850yt9hf1bg/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/include" -I"C:/Program Files/WindowsApps/51896DevPackager.DevCPP-CIDE_1.0.0.0_x64__6c850yt9hf1bg/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files/WindowsApps/51896DevPackager.DevCPP-CIDE_1.0.0.0_x64__6c850yt9hf1bg/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files/WindowsApps/51896DevPackager.DevCPP-CIDE_1.0.0.0_x64__6c850yt9hf1bg/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/include" -I"C:/Program Files/WindowsApps/51896DevPackager.DevCPP-CIDE_1.0.0.0_x64__6c850yt9hf1bg/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files/WindowsApps/51896DevPackager.DevCPP-CIDE_1.0.0.0_x64__6c850yt9hf1bg/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files/WindowsApps/51896DevPackager.DevCPP-CIDE_1.0.0.0_x64__6c850yt9hf1bg/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Juego_1.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
